### ISSUE TITLE
Google Colab version

### ISSUE THREAD

**Issue by danieltanhx** [Yujun-Shi/DragDiffusion#13]
To those who are struggling to replicate this. Below is the google colab version which can run on python3.10 linux google colab

!git clone https://github.com/Yujun-Shi/DragDiffusion.git
%cd /content/DragDiffusion
!pip install accelerate==0.17.0
!pip install transformers
!pip install diffusers
!pip install gradio
!pip install einops
!pip install pytorch_lightning
!mkdir /root/.cache/huggingface
!mkdir /root/.cache/huggingface/accelerate

string='''
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: 'NO'
downcast_bf16: 'no'
dynamo_config: {}
fsdp_config: {}
gpu_ids: '0'
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
'''
text_file = open("/root/.cache/huggingface/accelerate/default_config.yaml", "w")
n = text_file.write(string)
text_file.close()

!bash lora/train_lora.sh
!python drag_ui_real.py

**Comment by Yujun-Shi** [comment]
By the way, now we've integrate LoRA training into the user interface, so you don't need to go through the trouble of using "lora/train_lora.sh" :)

**Comment by Bendito999** [comment]
to get the colab version working again I had to change
!pip install accelerate==0.17.0
to
!pip install accelerate==0.20.3

**Comment by Toshik-One** [comment]
Gives this when you click on Train Lora
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/content/DragDiffusion/drag_ui_real.py", line 74, in train_lora_interface
    train_lora(
  File "/content/DragDiffusion/lora_utils.py", line 205, in train_lora
    text_embedding = encode_prompt(
  File "/content/DragDiffusion/lora_utils.py", line 93, in encode_prompt
    prompt_embeds = text_encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 823, in forward
    return self.text_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 741, in forward
    encoder_outputs = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 655, in forward
    layer_outputs = encoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 384, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by uranusx86** [comment]
Here is the conda version in the Google Colab.

## install condacolab package
```python
!pip install -q condacolab
import condacolab
condacolab.install()
import sys
print(sys.executable)
```

## clone the source code
```python
!git clone https://github.com/Yujun-Shi/DragDiffusion.git
```

## fix environment.yaml
```python
%cd /content/DragDiffusion
# fix cudatoolkit not found error
!sed -i '4 a \ \ - nvidia' environment.yaml
!sed -i '4 a \ \ - conda-forge' environment.yaml
```

## create runtime environment
```python
!conda env create -f environment.yaml
!source /usr/local/etc/profile.d/conda.sh
```

## install the missing package & run the demo
```python
!source activate dragdiff && pip install ipykernel && python -m ipykernel install --user && python drag_ui.py
```
