### ISSUE TITLE
宽高为559*801，run报错

### ISSUE THREAD

**Issue by gaoshangle** [Yujun-Shi/DragDiffusion#28]
下面是报错信息

DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:06<00:00,  7.86it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/2dragdiff/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/2dragdiff/lib/python3.8/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/2dragdiff/lib/python3.8/site-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/2dragdiff/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/2dragdiff/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/2dragdiff/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/2dragdiff/lib/python3.8/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/maiyuan/ai_project/gaoluoluo/DragDiffusion/utils/ui_utils.py", line 277, in run_drag
    save_result = torch.cat([
RuntimeError: Sizes of tensors must match except in dimension 3. Expected size 733 but got size 512 for tensor number 1 in the list.

![image](https://github.com/Yujun-Shi/DragDiffusion/assets/37358834/241562aa-83bd-452d-817e-4d4fa595ef39)

**Comment by Yujun-Shi** [comment]
hello, 感谢feedback，这是一个小bug，刚刚已经fix了哈
