### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by christopherquenneville** [Yujun-Shi/DragDiffusion#36]
C:\StableDiffusion\DragDiffusion>python drag_ui.py
Traceback (most recent call last):
  File "C:\StableDiffusion\DragDiffusion\drag_ui.py", line 22, in <module>
    from utils.ui_utils import get_points, undo_points
  File "C:\StableDiffusion\DragDiffusion\utils\ui_utils.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

I am getting this error from CMD when trying to launch the GUI script.

Am I missing something?

Thanks for your help in advance,
Good day

**Comment by christopherquenneville** [comment]
It looks like opencv-contrib-python 4.3.0.36 was yanked
https://pypi.org/project/opencv-contrib-python/4.3.0.36/

**Comment by christopherquenneville** [comment]
Fixed my problem by installing the following:
pip install opencv-python

And then I also had to install others:
pip install einops
pip install pytorch-lightning
pip install accelerate
pip install transformers
