### ISSUE TITLE
训练lora出现错误

### ISSUE THREAD

**Issue by shijiunianhua123** [Yujun-Shi/DragDiffusion#41]
![屏幕截图 2023-10-11 210425](https://github.com/Yujun-Shi/DragDiffusion/assets/129756878/885f1470-f351-4c2a-98b8-b7079e076e60)
感谢您的代码，但是我在上传自己的图片时出现了错误，我的gpu是3060ti，麻烦你解答一下

**Comment by Yujun-Shi** [comment]
你好，可以麻烦把命令行的错误信息发一下吗，谢谢

**Comment by shijiunianhua123** [comment]
> 你好，可以麻烦把命令行的错误信息发一下吗，谢谢

感谢你的回复，麻烦你帮我看一下
Running on local URL:  http://127.0.0.1:7860
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /runwayml/stable-diffusion-v1-5/resolve/main/tokenizer/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025408376AC8>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 35d23841-d8e4-493c-ad39-758db3e47f1c)')' thrown while requesting HEAD https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/tokenizer/tokenizer_config.json

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app. 

Also please ensure that your antivirus or firewall is not blocking the binary file located at: C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\gradio\frpc_windows_amd64_v0.2
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /runwayml/stable-diffusion-v1-5/resolve/main/tokenizer/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002540837A5C8>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: b61ef5f8-c7c0-4331-84a8-079677ceda7e)')' thrown while requesting HEAD https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/tokenizer/config.json
Traceback (most recent call last):
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\transformers\utils\hub.py", line 429, in cached_file
    local_files_only=local_files_only,
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\huggingface_hub\file_download.py", line 1292, in hf_hub_download
    "Connection error, and we cannot find the requested files in"
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\gradio\routes.py", line 444, in run_predict
    event_data=event_data,
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\gradio\blocks.py", line 1347, in process_api
    fn_index, inputs, iterator, request, event_id, event_data
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\gradio\blocks.py", line 1075, in call_function
    fn, *processed_input, limiter=self.limiter
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\anyio\to_thread.py", line 34, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\code\DragDiffusion-main\utils\ui_utils.py", line 143, in train_lora_interface
    progress)
  File "D:\code\DragDiffusion-main\utils\lora_utils.py", line 132, in train_lora
    use_fast=False,
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 659, in from_pretrained
    pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\transformers\models\auto\configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\transformers\configuration_utils.py", line 641, in _get_config_dict
    _commit_hash=commit_hash,
  File "C:\Users\shijiu\.conda\envs\xmj_2\lib\site-packages\transformers\utils\hub.py", line 453, in cached_file
    f"We couldn't connect to '{HUGGINGFACE_CO_RESOLVE_ENDPOINT}' to load this file, couldn't find it in the"
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like runwayml/stable-diffusion-v1-5 is not the path to a directory containing a file named tokenizer\config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by shijiunianhua123** [comment]
你好，感谢你的回复，我出现的问题是这样的：

因为huggingface锁国区了，所以我只能开代理，但是不知为啥，即使这次下载好了，下一次还是要重新下载，如果可以可不可以加你的QQ或者微信，我们聊一聊，麻烦你了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yujun-Shi/DragDiffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 凌晨0:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yujun-Shi/DragDiffusion] 训练lora出现错误 (Issue #41)





 
你好，可以麻烦把命令行的错误信息发一下吗，谢谢
